#!/usr/bin/env bash

COMPONENT=${1}

#
#   usage
#
usage() {

    echo "usage: ./rerun config:component <component-name> [--run | --export-to <directory>]"
    echo
}

#
#   list_available_components
#
list_available_components() {

    for component in $(find ${RERUN_COMMAND_DIR%%/}/configs/* -type d)
    do
        echo ${component}
    done
}

#
#   main
#

[ -z ${COMPONENT} ] && {
    usage

    echo -n "List of available components: "
    for component in $(list_available_components)
    do
        echo -n "$(basename ${component} .config) "
    done
    echo
    exit 1
}

[ -f ${RERUN_COMMAND_DIR%%/}/configs/${COMPONENT}/script ] && {
        . ${RERUN_COMMAND_DIR%%/}/configs/${COMPONENT}/script
} || {
    echo "** Error! Component name does not founded: ${COMPONENT}"
    exit 1
}

