#!/usr/bin/env bash
#

RUNLEVEL="rc0"

. ${RERUN_MODULES%%/}/lib/service-functions.sh     

#
#   run 
#
run() {

    for level in $(ls ${RERUN_MODULES})
    do
        ( [[ ${level} == rc* ]] && [[ ${level} != "rc0" ]] ) && {

            [ -d ${RERUN_MODULES%%/}/${level}/commands/ ] && {
                for command in $(ls ${RERUN_MODULES%%/}/${level}/commands/ )
                do
                    ${RERUN} ${level}:${command} --run
                done
            }
        }
    done
}

# ==============================================
#   Main script
# ----------------------------------------------
handle_command_options "$@"

